name: Tests

on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'

jobs:
  test:
    name: "GraphQL-Ruby ${{ matrix.graphql }} (interpreter: ${{ matrix.interpreter }} with AnyCable ${{ matrix.anycable }}, use_client_id: ${{ matrix.client_id }}) on Ruby ${{ matrix.ruby }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: "3.0"
            graphql: '~> 1.12.0'
            anycable: '~> 1.1.0'
            client_id: 'false'
            interpreter: yes
          - ruby: 2.7
            graphql: '~> 1.12.0'
            anycable: '~> 1.1.0'
            client_id: 'false'
            interpreter: yes
          - ruby: 2.6
            graphql: '~> 1.11.0'
            anycable: '~> 1.0.0'
            client_id: 'true'
            interpreter: no
    container:
      image: ruby:${{ matrix.ruby }}
      env:
        CI: true
        GRAPHQL_RUBY_VERSION: ${{ matrix.graphql }}
        ANYCABLE_VERSION: ${{ matrix.anycable }}
        GRAPHQL_ANYCABLE_USE_CLIENT_PROVIDED_UNIQ_ID: ${{ matrix.client_id }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: bundle-${{ matrix.ruby }}-${{ matrix.graphql }}-${{ matrix.anycable }}-${{ hashFiles('**/*.gemspec') }}-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            bundle-${{ matrix.ruby }}-${{ matrix.graphql }}-${{ matrix.anycable }}-
            bundle-${{ matrix.ruby }}-
      - name: Upgrade Bundler to 2.0 (for older Rubies)
        run: gem install bundler -v '~> 2.0'
      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install
          bundle update
      - name: Run RSpec
        env:
          GRAPHQL_RUBY_INTERPRETER: ${{ matrix.interpreter }}
        run: bundle exec rspec
