name: Tests

on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'

jobs:
  test:
    name: "GraphQL-Ruby ${{ matrix.graphql }} AnyCable ${{ matrix.anycable }} on Ruby ${{ matrix.ruby }} Redis ${{ matrix.redis_version }}"
    # Skip running tests for local pull requests (use push event instead), run only for foreign ones
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.owner.login != github.event.pull_request.base.repo.owner.login
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: "3.3"
            graphql: '~> 2.3'
            anycable: '~> 1.5'
            redis_version: latest
          - ruby: "3.2"
            graphql: '~> 2.2.0'
            anycable: '~> 1.4.0'
            redis_version: '7.2'
          - ruby: "3.1"
            graphql: '~> 2.0.0'
            anycable: '~> 1.3.0'
            redis_version: '6.2'
    env:
      CI: true
      GRAPHQL_RUBY_VERSION: ${{ matrix.graphql }}
      ANYCABLE_VERSION: ${{ matrix.anycable }}
      ANYCABLE_RAILS_VERSION: ${{ matrix.anycable }}
      GRAPHQL_ANYCABLE_USE_CLIENT_PROVIDED_UNIQ_ID: ${{ matrix.client_id }}
      REDIS_URL: redis://localhost:6379
    services:
      redis:
        image: redis:${{ matrix.redis_version }}
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run RSpec
        run: bundle exec rspec
